Akshita_K_301107284/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Jasmine_Soccer.Models;
using Microsoft.AspNetCore.Mvc;


namespace Jasmine_Soccer.Controllers
{
    public class ClubController : Controller
    {

        private IClubRepository clubRepo;
        private IPlayerRepository playerRepo;

        public ClubController(IClubRepository clubRepository, IPlayerRepository playerRepository)
        {
            clubRepo = clubRepository;
            playerRepo = playerRepository;
        }

        public ViewResult ClubList()
        {
            IEnumerable<Club> clubs = clubRepo.GetClubs();
            return View(clubs);
        }

        [HttpPost]
        public ViewResult AddClub(Club club)
        {
            clubRepo.SaveClub(club);

            Player player = playerRepo.GetPlayer(club.YourName);

            if (player != null)
            {
                player.ClubName = club.ClubName;
                playerRepo.SavePlayer(player);
            }

            TempData["message"] = $"Club {club.ClubName} saved!";

            return View(club);
        }

        [HttpGet]
        public ViewResult AddClub(int clubId)
        {
            Club club = clubRepo.GetClub(clubId);
            return View(club);
        }

        public IActionResult RemoveClub(int clubId)
        {
            Club club = clubRepo.GetClub(clubId);

            if (club != null)
            {
                clubRepo.DeleteClub(club);
                TempData["message"] = $"Club {club.ClubName} deleted!";
            }

            return RedirectToAction("ClubList");
        }

        public ViewResult AddClub()
        {
            return View();
        }

        public ViewResult ClubDetails()
        {
            return View();
        }

        [HttpGet]
        public ViewResult ClubDetails(int clubId)
        {
            Club club = clubRepo.GetClub(clubId) ;
            club.Players = playerRepo.GetPlayers(club.ClubName);

            return View(club);
        }

    }
}

Akshita_K_301107284/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Jasmine_Soccer.Models;
using Microsoft.AspNetCore.Mvc;

namespace Jasmine_Soccer.Controllers
{
    public class PlayerController : Controller
    {

        private IPlayerRepository playerRepo;

        public PlayerController(IPlayerRepository playerRepository)
        {
            playerRepo = playerRepository;
        }

        public ViewResult PlayersPage()
        {
            return View();
        }
        public ViewResult PlayerList()
        {

            IEnumerable<Player> players = playerRepo.GetPlayers();
            return View(players);

        }
       
        public ViewResult Reassign(string clubName)
        {
            Player player = new Player();
            player.ClubName = clubName;
            return View(player);
        }

        [HttpPost]
        public ViewResult Reassign(Player player)
        {
            Player dbPlayer = playerRepo.GetPlayer(player.PlayerName);
            string playerName = player.PlayerName;

            if (dbPlayer != null)
            {
                dbPlayer.ClubName = player.ClubName;
                playerRepo.SavePlayer(dbPlayer);
                TempData["message"] = $"Player {playerName} updated!";
            }
            else
            {
                TempData["message"] = $"Player {playerName} not found.";
            }

            return View();
        }
        public ViewResult Delete()
        {
            return View();
        }
    }
}

Akshita_K_301107284/Views/Shared/AddClubPartial.cshtml
@model Club

     <form asp-action="AddClub" method="post">
        <input type="hidden" asp-for="@Model.ClubId" />
        <label asp-for="ClubName">Name of the Club:</label>
        <input class="form-style" asp-for="ClubName">

        <label asp-for="YourName">Your Name</label>
        <input class="form-style" asp-for="YourName">

        <label asp-for="AgeGroup">Age Group</label>
        <input class="form-style" asp-for="AgeGroup">

        <div align="center">
        <input class="submit-style submit-style-hover"  type="submit" value="Save">
        <input class="submit-style submit-style-hover"  type="submit" value="Cancel" asp-action="Index" asp-controller="Home" />
        </div>
     </form>

Akshita_K_301107284/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link href="~/css/CustomStyle.css" rel="stylesheet" />

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <img style="width: 80px; height:60px;margin-top: 15px; margin-left:15px;" src="~/images/logo_fotball_shield_1661825.jpg" />
        <a class="navbar-brand" href="#">    Soccer Club Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">   Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Club" asp-action="ClubList">Club</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Club" asp-action="AddClub">Add Club</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Player" asp-action="PlayersPage">Manage Players</a>
                </li>
            </ul>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>
</html>